#! /bin/sh

egg_locations_uri="http://code.call-cc.org/svn/chicken-eggs/release/4/egg-locations"
egg_locations_file=`mktemp`
bb_download_dir=`bitbake -e | grep ^DL_DIR | sed 's/DL_DIR *= *"\(.*\)\"/\1/'`

if [ -z "$bb_download_dir" ]; then
    echo "Could not determine bitbake's DL_DIR value.  Aborting."
    exit 1
fi

cache_dir=$bb_download_dir/henrietta-cache

trap "rm -f $egg_locations_file; exit" INT TERM EXIT

wget -O $egg_locations_file --user=anonymous --password= $egg_locations_uri

henrietta-cache -c $cache_dir -e $egg_locations_file
